### ISSUE TITLE
Multi-instrument source separation

### ISSUE THREAD

**Issue by yangdaowu** [ws-choi/ISMIR2020_U_Nets_SVS#4]
Hello, I would like to know how to implement multi-instrument source separation, I only want to use this code, thank you

**Comment by ws-choi** [comment]
Hi @yangdaowu ,
Unfortunately, this model is dedicated to a single-source separation, which means that it cannot support multi-source separation with a single instance. Alternatively, you can train an individual model for each source.
For example, if there are 5 sources, then simply make 5 instances based on this architecture and train them separately for each task. To do so, you can customize this package: https://github.com/ws-choi/ISMIR2020_U_Nets_SVS/tree/master/source_separation/data. All you need is to build your own data loader for your task.

Good luck!
