### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by ujscjj** [ws-choi/ISMIR2020_U_Nets_SVS#5]
Hello, Thank you for your sharing codes.

Could you please tell me how long does it take you to train this model (TFC_TDF_Net (large))?
In my setup, one 2080ti, batch_size=8, it takes 12 minutes for every epoch. It means that I need to wait 17 days for 2000 epochs. It looks like unreasonable. Is this the same as your training time?

Looking forward to you.

**Comment by ws-choi** [comment]
Hi @ujscjj,

A large version of the TFC_TDF_Net is quite large.
I don't recall it exactly, but it takes at least four days to train on four ```2080ti```s.
Unfortunately, if you are using a single ```2080ti```, you may wait more than two weeks for the convergence.

**Comment by ujscjj** [comment]
Got it. Thank you.
